#!/system/bin/sh

dir="${0%/*}"
tmpDaemonApk="/data/local/tmp/daemon.apk"
debug="@DEBUG@"

# Bezpiecznie sprawdź debugowanie APK i ustaw ścieżkę klasy
if [ -r "$tmpDaemonApk" ]; then
  java_options="-Djava.class.path=$tmpDaemonApk"
  debug="true"
else
  java_options="-Djava.class.path=$dir/daemon.apk"
fi

# Zastosuj opcje debugowania na podstawie wersji Android SDK.
# Odniesienie: https://developer.android.com/ndk/guides/wrap-script#debugging_when_using_wrapsh
if [ "$debug" = "true" ]; then
  os_version=$(getprop ro.build.version.sdk)
  if [ "$os_version" -eq "27" ]; then
    java_options="$java_options -Xrunjdwp:transport=dt_android_adb,suspend=n,server=y -Xcompiler-option --debuggable"
  elif [ "$os_version" -eq "28" ]; then
    java_options="$java_options -XjdwpProvider:adbconnection -XjdwpOptions:suspend=n,server=y -Xcompiler-option --debuggable"
  else
    java_options="$java_options -XjdwpProvider:adbconnection -XjdwpOptions:suspend=n,server=y"
  fi
fi

# Zamontuj pusty tymczasowy system plików w /data/resource-cache, aby uniknąć potencjalnych konfliktów nakładek.
# Należy pamiętać, że ten skrypt działa w odizolowanej przestrzeni nazw montowania (za pośrednictwem unshare).
mount tmpfs -t tmpfs /data/resource-cache

# Poczekaj na gniazdo zygote, używając pętli sondowania
if [ ! -S "/dev/socket/zygote" ]; then
  # Poczekaj do ~10 sekund, aby uniknąć nieskończonego zawieszenia, jeśli coś się zepsuje
  wait_count=0
  while [ ! -S "/dev/socket/zygote" ] &&[ "$wait_count" -lt 100 ]; do
    sleep 0.1
    wait_count=$((wait_count + 1))
  done
  [ "$debug" = "true" ] && log -p v -t "Vector" "zygote uruchomiony"
fi

[ "$debug" = "true" ] && log -p d -t "Vector" "Uruchamianie daemon $*"

# Włącz daemon
exec /system/bin/app_process $java_options /system/bin --nice-name=lspd org.matrix.vector.daemon.VectorDaemon "$@" >/dev/null 2>&1
