name: Vector-PL-release

on:
  workflow_dispatch:
  push:
    branches: [ PL ]
    tags: [ 2.0 ]
  pull_request:
  merge_group:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: 'temurin'
        cache: 'gradle'

    - name: Write key
      if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/PL' || github.event_name == 'workflow_dispatch')
      run: |
        if [ ! -z "${{ secrets.SIGNING_KEY }}" ]; then
        echo releaseStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> gradle.properties
        echo releaseKeyAlias='${{ secrets.ALIAS }}' >> gradle.properties
        echo releaseKeyPassword='${{ secrets.KEY_PASSWORD }}' >> gradle.properties
        echo releaseStoreFile='key.jks' >> gradle.properties
        echo ${{ secrets.SIGNING_KEY }} | base64 --decode > key.jks
        fi

    - name: Accept Android SDK licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Patch Ninja for C++20 Modules
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build
        # Znajdujemy ścieżkę do systemowego ninja i nadpisujemy ten w SDK Androida
        SYSTEM_NINJA=$(which ninja)
        SDK_NINJA="/usr/local/lib/android/sdk/cmake/3.31.5/bin/ninja"
        sudo cp "$SYSTEM_NINJA" "$SDK_NINJA"
        sudo chmod +x "$SDK_NINJA"
        echo "Ninja patched successfully."

    - name: Build with Gradle
      run: ./gradlew assembleRelease assembleDebug -Dorg.gradle.jvmargs="-Xmx4g" --no-daemon

    - name: Rename zip
      run: |
        mkdir -p app/build/outputs/zip/release
        mkdir -p app/build/outputs/zip/debug
        # Uwaga: sprawdź czy pliki faktycznie tu lądują, jeśli nie - użyj find
        mv app/build/outputs/apk/release/*.apk app/build/outputs/zip/release/Vector-PL-2.0.3043-release.zip || true
        mv app/build/outputs/apk/debug/*.apk app/build/outputs/zip/debug/Vector-PL-2.0.3043-debug.zip || true

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: outputs
        path: app/build/outputs/zip

    - name: Upload to Releases
      if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/PL' || github.event_name == 'workflow_dispatch')
      uses: ncipollo/release-action@v1
      with:
        artifacts: "app/build/outputs/zip/release/Vector-PL-2.0.3043-release.zip,app/build/outputs/zip/debug/Vector-PL-2.0.3043-debug.zip"
        tag: "2.0"
        name: "Vector-PL 2.0.3043"
        allowUpdates: "true"
        token: "${{ secrets.GITHUB_TOKEN }}"
